## build project
#kind: pipeline
#type: docker
#name: build_production
#
##trigger:
##  event:
##    -push
##  branch:
##    -main
#
#steps:
#  - name: notify_about_start
#    image: appleboy/drone-discord
#    settings:
#      webhook_id:
#        from_secret: DISCORD_WEBHOOK_ID
#      webhook_token:
#        from_secret: DISCORD_WEBHOOK_TOKEN
#      username: billiard_bot
#      message: >
#        ⚙️ Production [deploy](<{{ build.link }}>) of `build ${DRONE_BUILD_PARENT}` of `{{repo.name}}`:`{{commit.branch}}`.
#  - name: build_production
#    image: appleboy/drone-ssh
#    volumes:
#      - name: docker_sock
#        path: /var/run/docker.sock
#    settings:
#      host:
#        from_secret: HOST_DOMAIN
#      username:
#        from_secret: HOST_USERNAME
#      port: 22
#      script:
#        - cd services/billiard
#        - make build-production
#
#
#  - name: start_production
#    image: appleboy/drone-ssh
#    volumes:
#      - name: docker_sock
#        path: /var/run/docker.sock
#    settings:
#      host:
#        from_secret: HOST_DOMAIN
#      username:
#        from_secret: HOST_USERNAME
#      port: 22
#      script:
#        - cd services/billiard
#        - make start-production


kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world