version: '3.8'

networks:
  proxy:
    attachable: true
    internal: false
    name: proxy

services:
  production_client:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: production_client
    restart: always
    networks:
      - proxy
    healthcheck:
      disable: true
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.production_client.entrypoints=websecure
      - traefik.http.routers.production_client.rule=Host(`www.epic-type.ru`,`epic-type.ru`, `pom-pom.pro`)
      - traefik.http.routers.production_client.tls=true
      - traefik.http.routers.production_client.tls.certresolver=letsencrypt
      - traefik.http.routers.production_client.service=production_client_service
      - traefik.http.services.production_client_service.loadbalancer.server.port=3000