version: '3.8'

networks:
  proxy:
    attachable: true
    internal: false
    name: proxy

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    restart: always
    healthcheck:
      disable: true
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.with-docker-multi-env-production.entrypoints=websecure
      - traefik.http.routers.with-docker-multi-env-production.tls.certresolver=letsencrypt
      - traefik.http.routers.with-docker-multi-env-production.rule=Host(`www.epic-type.ru`,`epic-type.ru`)
      - traefik.http.routers.with-docker-multi-env-production.tls=true
      - traefik.http.routers.with-docker-multi-env-production.service=with-docker-multi-env-production_service
      - traefik.http.services.with-docker-multi-env-production_service.loadbalancer.server.port=3000